enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[VSCO]
app-name = "VSCO"
build-mode = "apk"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.vsco.cam"
arch = "arm-v7a"
version = "324"

[Lightroom]
app-name = "Lightroom"
build-mode = "apk"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.adobe.lrmobile"
arch = "arm-v7a"
version = "9.0.0"