enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[VSCO]
enabled = false
app-name = "VSCO"
build-mode = "apk"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.vsco.cam"
arch = "arm-v7a"
version = "auto"

[Lightroom]
app-name = "Lightroom"
build-mode = "apk"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.adobe.lrmobile"
uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.adobe.lrmobile/"
arch = "arm-v7a"
version = "auto"